# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Naeun Kim
title: ITì‹œëŒ€ë¥¼ ì„ ë„í•  ìˆ˜ ìˆëŠ” ê°œë°œìê°€ ë˜ê³  ì‹¶ìŠµë‹ˆë‹¤.
email: skdms8827@naver.com
# email_title: Email (Email title override)
phone: 010.9278.3768
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: skdms8827


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.PNG
about_content: | # this will include new lines to allow paragraphs
  > #### âœ¨ **&nbsp;ì €ëŠ” ì–´ë–¤ ë¬¸ì œë“  ê² ë¨¹ì§€ ì•Šê³  ë„ì „í•©ë‹ˆë‹¤.**
   
  > #### âœ¨**&nbsp;ì–¸ì œë‚˜ ë°°ìš°ê³  íƒêµ¬í•˜ë ¤ëŠ” ìì„¸ë¥¼ ê°–ì¶”ê³  ìˆìŠµë‹ˆë‹¤.**
  
  > #### âœ¨**&nbsp;ì½”ë”©ê³¼ ë””ë²„ê¹…í•˜ëŠ” ê²ƒì„ ì¦ê¸°ê³  ìˆìŠµë‹ˆë‹¤.**
  
  > #### âœ¨**&nbsp;ë¬´í•œí•œ ê°€ëŠ¥ì„±ê³¼ ì ì¬ë ¥ì„ ê°€ì§€ê³  ìˆìŠµë‹ˆë‹¤.**
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: **ê°œì¸ ë§ì¶¤ ì¥í•™ê¸ˆ ì¶”ì²œ ì• í”Œë¦¬ì¼€ì´ì…˜**
        link: skdms8827/ShcolarLike
        link_text: #####ì¥í•™ë¼ì´í¬ ë³´ëŸ¬ê°€ê¸°

        description: | # this will include new lines to allow paragraphs
          #### **ê¸°ì¤€ì´ ê¹Œë‹¤ë¡­ê³  ë†“ì¹˜ê¸° ì‰¬ìš´ ì¥í•™ê¸ˆ. ê¸°ë³¸ ì •ë³´ë§Œ ì…ë ¥í•˜ë©´ ìˆ˜í˜œí•  ìˆ˜ ìˆëŠ” ì¥í•™ê¸ˆ ë¦¬ìŠ¤íŠ¸ ì œê³µ**<br/><br/>
          - #### ì½”í‹€ë¦° ê¸°ë°˜ ì•ˆë“œë¡œì´ë“œ ìŠ¤íŠœë””ì˜¤
          - #### íŒŒì´ì–´ë² ì´ìŠ¤ë¡œ ë°ì´í„° ì €ì¥ ë° ê´€ë¦¬
          
          ![alt text](/images/scholar2.jpg)
          
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ì „êµ­ ê³µí•­ì˜ ì£¼ì°¨ì¥<br/> í˜¼ì¡ë„
        link: skdms8827/ShcolarLike
        link_text:  ##### ì£¼ì°¨ì¥ í˜¼ì¡ë„ ë³´ëŸ¬ê°€ê¸°

        description: | # this will include new lines to allow paragraphs
          #### **ì‹¤ì‹œê°„ìœ¼ë¡œ ì „êµ­ ê³µí•­ì˜ í˜¼ì¡ë„ë¥¼ í•œ ëˆˆì— í™•ì¸í•  ìˆ˜ ìˆë„ë¡ êµ¬í˜„.**<br/><br/>
          - #### MQTT í”„ë¡œí† ì½œ ê¸°ë°˜ êµ¬ë…ê³¼ ë°œí–‰ìœ¼ë¡œ êµ¬í˜„.
          - #### MongoDBë¡œ ë°ì´í„° ì €ì¥ ë° ê´€ë¦¬
          
          
          ![alt text](/images/mqtt1.jpg)
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ë¸”ë¡œê·¸ ë§Œë“¤ê¸°
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: HTML CSS JavaScript

        description: | # this will include new lines to allow paragraphs
          #### HTML CSS JavaScriptë¥¼ ì‚¬ìš©í•˜ì—¬ ê°„ë‹¨í•œ ë¸”ë¡œê·¸ë¥¼ ë§Œë“¤ì–´ ë³´ì•˜ë‹¤!
          
          ![alt text](/images/vlog.jpg)
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ì¥ì• ë¬¼ í”¼í•˜ê¸° ê²Œì„
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: WebGL

        description: | # this will include new lines to allow paragraphs
          #### WebGL ê¸°ë°˜ìœ¼ë¡œ ê°„ë‹¨í•œ ê²Œì„ êµ¬í˜„!
          
          ![alt text](/images/webgl.jpg)
 
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Hallym University
        sub_title: ì»´í“¨í„°ê³µí•™/ë¹…ë°ì´í„°ì „ê³µ
        caption: 2018.3 ~
        quote: >
      
        description: | # this will include new lines to allow paragraphs
          - #### **2018**
            - ì»´í“¨í„°ê³µí•™ê³¼ í•™ìƒíšŒ í™ë³´ë¶€ì› <br/>
            
          - #### **2019**
            - ì»´í“¨í„°ê³µí•™ê³¼ í•™ìƒíšŒ í™ë³´êµ­ì¥
            - í•™ìˆ ë™ì•„ë¦¬ NONAME ì„ì›<br/>
            - spinoff SW ì°½ì—… ë™ì•„ë¦¬ 
            -
          - #### **2022**
            - ì†Œí”„íŠ¸ìœµí•©ëŒ€í•™ í•™ìƒíšŒ ë³µì§€ë¶€ì›     
            - ì¤‘ì•™ì„ ê±°ê´€ë¦¬ìœ„ì›íšŒ ë¶€ìœ„ì›ì¥<br/>
            
          - #### **ì „ê³µìˆ˜ì—…**
            - ì»´í“¨í„° ë„¤íŠ¸ì›Œí¬, ë¨¸ì‹ ëŸ¬ë‹, ë°ì´í„°ë² ì´ìŠ¤ ê¸°ì´ˆ, ìš´ì˜ì²´ì œ ë“±
            
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ### ğŸ’« <mark>ìˆ˜ìƒê²½ë ¥</mark>
      - 2022 ìº¡ìŠ¤í†¤ë””ìì¸ ì€ìƒ ìˆ˜ìƒ
      - 2021 ì°½ì—…ì•„ì´ë””ì–´ ê²½ì§„ëŒ€íšŒ ê¸ˆìƒ ìˆ˜ìƒ
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
