# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Naeun Kim
title: ITì‹œëŒ€ë¥¼ ì„ ë„í•  ìˆ˜ ìˆëŠ” ê°œë°œìê°€ ë˜ê³  ì‹¶ìŠµë‹ˆë‹¤.
email: skdms8827@naver.com
# email_title: Email (Email title override)
phone: 010.9278.3768
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: skdms8827


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.PNG
about_content: | # this will include new lines to allow paragraphs
  > #### ___""ë‚˜ì˜ ê°€ëŠ¥ì„±ì€ ë‚´ê°€ ë§Œë“¤ì–´ ë‚¸ë‹¤.""___<br/><br/>

  > #### âœ¨ **&nbsp;ì €ëŠ” ì–´ë–¤ ë¬¸ì œë“  ê² ë¨¹ì§€ ì•Šê³  ë„ì „í•©ë‹ˆë‹¤.**
   
  > #### âœ¨**&nbsp;ì–¸ì œë‚˜ ë°°ìš°ê³  íƒêµ¬í•˜ë ¤ëŠ” ìì„¸ë¥¼ ê°–ì¶”ê³  ìˆìŠµë‹ˆë‹¤.**
  
  > #### âœ¨**&nbsp;ì½”ë”©ê³¼ ë””ë²„ê¹…í•˜ëŠ” ê²ƒì„ ì¦ê¸°ê³  ìˆìŠµë‹ˆë‹¤.**
  
  > #### âœ¨**&nbsp;ë¬´í•œí•œ ê°€ëŠ¥ì„±ê³¼ ì ì¬ë ¥ì„ ê°€ì§€ê³  ìˆìŠµë‹ˆë‹¤.**
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ê°œì¸ ë§ì¶¤ ì¥í•™ê¸ˆ ì¶”ì²œ ì• í”Œë¦¬ì¼€ì´ì…˜
        link: #
        link_text: 

        description: | # this will include new lines to allow paragraphs
          #### **ì‚¬ìš©ìì˜ ì¡°ê±´ì— ë§ëŠ” ì¥í•™ê¸ˆì„ ì°¾ì•„ì£¼ëŠ” ì• í”Œë¦¬ì¼€ì´ì…˜ "ì¥í•™ë¼ì´í¬"**<br/><br/>
          #### __ì‚¬ìš©ìê°€ ì…ë ¥í•˜ëŠ” ì¡°ê±´ìœ¼ë¡œ ìˆ˜í˜œí•  ìˆ˜ ìˆëŠ” ì¥í•™ê¸ˆì„ ì°¾ëŠ” ë©”ì¸ ê¸°ëŠ¥ ë‹´ë‹¹__<br/><br/>
          #### - ì½”í‹€ë¦° ê¸°ë°˜ ì•ˆë“œë¡œì´ë“œ ìŠ¤íŠœë””ì˜¤
          #### - íŒŒì´ì–´ë² ì´ìŠ¤ë¡œ ë°ì´í„° ì €ì¥ ë° ê´€ë¦¬<br/><br/> 
          
          ![alt text](/images/scholar2.jpg)
          
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ì „êµ­ ê³µí•­ì˜ ì£¼ì°¨ì¥ í˜¼ì¡ë„
        link: #
        link_text:

        description: | # this will include new lines to allow paragraphs
          #### **ì‹¤ì‹œê°„ìœ¼ë¡œ ì „êµ­ ì£¼ì°¨ì¥ì˜ í˜¼ì¡ë„ë¥¼ í•œëˆˆì— í™•ì¸í•  ìˆ˜ ìˆëŠ” ì„œë¹„ìŠ¤**<br/><br/> 
          
          #### - MQTT í”„ë¡œí† ì½œì„ ì‚¬ìš©í•˜ì—¬ ë°ì´í„° êµ¬ë…ê³¼ ë°œí–‰
          #### - MongoDBë¥¼ ì‚¬ìš©í•˜ì—¬ ë°ì´í„° ì €ì¥ ë° ê´€ë¦¬<br/><br/>
          
          ![alt text](/images/mqtt1.jpg)
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ë¸”ë¡œê·¸ ì œì‘ ì›¹í”„ë¡œê·¸ë˜ë°
        link: #
        link_text: 

        description: | # this will include new lines to allow paragraphs
          #### **í”„ë¡œì íŠ¸ ì†Œê°œì™€ ë¬¸ì œ í•´ê²° ê³¼ì •ì„ ë¸”ë¡œê·¸ë¡œ êµ¬í˜„**<br/><br/>
          #### - HTML, CSS, JavaScriptë¥¼ ì‚¬ìš©í•˜ì—¬ ê°œë°œ<br/><br/>
          
          ![alt text](/images/vlog.jpg)
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ì†Œí”„íŠ¸ì›¨ì–´ ì „ì‹œíšŒ
        link: #
        link_text:

        description: | # this will include new lines to allow paragraphs
          #### **í•™ìˆ ë™ì•„ë¦¬ ì”¨ì• ë‘ ë™ì•„ë¦¬ì˜ ì†Œí”„íŠ¸ì›¨ì–´ ì „ì‹œíšŒ í™ˆí˜ì´ì§€**<br/><br/>
          #### "íŒ€ë³„ ì‘í’ˆ ì†Œê°œ, ì‘í’ˆ ë“±ë¡ ë° ìˆ˜ì • í˜ì´ì§€ êµ¬í˜„"<br/><br/>
          #### - HTML, CSS, JavaScriptë¥¼ ì´ìš©í•œ ì›¹ í”„ë¡œê·¸ë˜ë°
          #### - ë°˜ì‘í˜• ì›¹ ì„œë¹„ìŠ¤ êµ¬í˜„<br/><br/>
        
          ![alt text](/images/webgl.jpg)
 
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Hallym University
        sub_title: ì»´í“¨í„°ê³µí•™/ë¹…ë°ì´í„°ì „ê³µ
        caption: 2018.3 ~
        quote: >
      
        description: | # this will include new lines to allow paragraphs
          ### <mark>2018<mark/>
            - ### ì»´í“¨í„°ê³µí•™ê³¼ í•™ìƒíšŒ í™ë³´ë¶€ì¥
              #### __- í•™ê³¼ ë‚´ í–‰ì‚¬ ê³µì§€ì‚¬í•­ PPT ì œì‘__<br/><br/>
           
          ### <mark>2019<mark/>
            - ### ì»´í“¨í„°ê³µí•™ê³¼ í•™ìƒíšŒ í™ë³´êµ­ì¥
              #### - í•™ê³¼ ë‚´ í–‰ì‚¬ ê³µì§€ì‚¬í•­ PPT ì œì‘<br/><br/>
              
            - í•™ìˆ ë™ì•„ë¦¬ NONAME ì„ì›
              #### - ìŠ¤í„°ë””ê·¸ë£¹ ê°œìµœ
              #### - ê°„ì‹ ì‚¬ì—…, ìŠ¤í„°ë””ê·¸ë£¹ ëŒ€íšŒ ë“± ê°ì¢… í–‰ì‚¬ ê¸°íš<br/><br/>
              
          ### <mark>2021<mark/>
            - spinoff SW ì°½ì—… ë™ì•„ë¦¬ "ì¥í•™ë¼ì´í¬"
              #### - ë©”ì¸ ê¸°ëŠ¥ ë‹´ë‹¹
              #### - ê°œì¸ ë§ì¶¤ ì¥í•™ê¸ˆ ì¶”ì²œ ì• í”Œë¦¬ì¼€ì´ì…˜
              #### - ì½”í‹€ë¦° ê¸°ë°˜ ì• í”Œë¦¬ì¼€ì´ì…˜ ê°œë°œ              
            
          ### <mark>2022<mark/>
            - ì†Œí”„íŠ¸ìœµí•©ëŒ€í•™ í•™ìƒíšŒ ë³µì§€ë¶€ì›
              #### - ë³µì§€ë¬¼í’ˆ êµ¬ë§¤ ë° ê´€ë¦¬
              #### - ê°œê°•ì‚¬ì—…, ì²´ìœ¡ëŒ€íšŒ, í˜ìŠ¤í‹°ë²Œ, í•™ìˆ ì œ ë“± ê°ì¢… í–‰ì‚¬ ê¸°íš ë° ì§„í–‰<br/><br/>
            - ì¤‘ì•™ì„ ê±°ê´€ë¦¬ìœ„ì›íšŒ ë¶€ìœ„ì›ì¥
              #### - ì…í›„ë³´ì ë“±ë¡ ê´€ë¦¬
              #### - ì„ ê±° ì¼ì • ë° ë°©ì‹ ê¸°íš
              #### - í›„ë³´ì ê³µì²­íšŒ ë° í† ë¡ íšŒ ì§„í–‰
            
          - ### <mark>ì „ê³µ ìˆ˜ì—…<mark/>
            | ì»´í“¨í„° ë„¤íŠ¸ì›Œí¬ | IoT ë„¤íŠ¸ì›Œí¬ | ìš´ì˜ì²´ì œ | ì›¹í”„ë¡œê·¸ë˜ë° |
            | ì»´í“¨í„°êµ¬ì¡° | SW ê°œë°œë„êµ¬ ì‘ìš© | ì˜¤í”ˆì†ŒìŠ¤ ë¦¬ëˆ…ìŠ¤ ì‹¤ë¬´ | ë¨¸ì‹ ëŸ¬ë‹|
            | C++ í”„ë¡œê·¸ë˜ë° | SW í•˜ë“œì›¨ì–´ ì‘ìš© | ì¸ê³µì§€ëŠ¥ | ì»´í“¨í„° ê·¸ë˜í”½ìŠ¤ |
            
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ### ğŸ’« <mark>ìˆ˜ìƒê²½ë ¥</mark>
      - 2022 ìº¡ìŠ¤í†¤ë””ìì¸ ì€ìƒ ìˆ˜ìƒ
      - 2021 ì°½ì—…ì•„ì´ë””ì–´ ê²½ì§„ëŒ€íšŒ ê¸ˆìƒ ìˆ˜ìƒ
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
